apiVersion: apps/v1
kind: Deployment
metadata:
  name: flickr-indexer
  namespace: contourguessr
  labels:
    app: flickr-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flickr-indexer
  template:
    metadata:
      labels:
        app: flickr-indexer
    spec:
      containers:
        - name: flickr-indexer
          image: ghcr.io/dzfranklin/cg-flickr-indexer:v0.11
          env:
            - name: FLICKR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: flickr-api-key
                  key: key
            - name: FLICKR_ENDPOINT
              value: "http://server.flickr-api-proxy.svc.cluster.local"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cg-database
                  key: url
