apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorer
  namespace: contourguessr
  labels:
    app: scorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scorer
  template:
    metadata:
      labels:
        app: scorer
    spec:
      containers:
        - name: scorer
          image: ghcr.io/dzfranklin/cg-scorer:v0.3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cg-database
                  key: url
            - name: OVERPASS_ENDPOINT
              value: "http://api.overpass.svc.cluster.local/api"
            - name: CLASSIFIER_ENDPOINT
              value: "http://classifier"
