ALTER TABLE regions
    ADD COLUMN min_lng DOUBLE PRECISION GENERATED ALWAYS AS (ST_XMin(geo::geometry)) STORED;
ALTER TABLE regions
    ADD COLUMN max_lng DOUBLE PRECISION GENERATED ALWAYS AS (ST_XMax(geo::geometry)) STORED;
ALTER TABLE regions
    ADD COLUMN min_lat DOUBLE PRECISION GENERATED ALWAYS AS (ST_YMin(geo::geometry)) STORED;
ALTER TABLE regions
    ADD COLUMN max_lat DOUBLE PRECISION GENERATED ALWAYS AS (ST_YMax(geo::geometry)) STORED;
